/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jenudai;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Arrays;
import java.util.Calendar;
import javax.swing.table.TableModel;
import static jenudai.JDBCConnection.conn;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author sandeep
 */
public class ViewRecords extends javax.swing.JFrame {

    /**
     * Creates new form ViewRecords
     */
    public ViewRecords() {
        initComponents();
        Calendar today = Calendar.getInstance();

        jDateChooser1.setDate(today.getTime());

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Delete = new javax.swing.JButton();
        allButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        loadButton = new javax.swing.JButton();
        addAmountButton = new javax.swing.JButton();
        viewBillButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        allButton.setText("All");
        allButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allButtonActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Invoice", "Goods", "Quantity", "Customer", "Type", "Price per Unit", "Total", "Cash", "Credit"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        loadButton.setText("Load");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        addAmountButton.setText("Add Amount");
        addAmountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAmountButtonActionPerformed(evt);
            }
        });

        viewBillButton.setText("View bill");
        viewBillButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBillButtonActionPerformed(evt);
            }
        });

        updateButton.setText("update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addAmountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(viewBillButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(allButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(loadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(allButton)
                        .addComponent(addAmountButton)
                        .addComponent(viewBillButton)
                        .addComponent(updateButton))
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loadButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void allButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allButtonActionPerformed
        // TODO add your handling code here:
       loadData(true);

    }//GEN-LAST:event_allButtonActionPerformed

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        // TODO add your handling code here
        try{
           new java.sql.Date(jDateChooser1.getDate().getTime());
           loadData(false);

        }
        catch(Exception e){
          Popup popup=new Popup("please select date");
            popup.setVisible(true);
            popup.setDefaultCloseOperation(DISPOSE_ON_CLOSE);  
        }
        
    }//GEN-LAST:event_loadButtonActionPerformed

    private void addAmountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAmountButtonActionPerformed
        // TODO add your handling code here:
        int[] selectedRow = jTable1.getSelectedRows();
        try{
        DataEntryForm2 dataEntryForm2=new DataEntryForm2(jTable1.getValueAt(selectedRow[0], 1).toString(),
                jTable1.getValueAt(selectedRow[0],2).toString());
        dataEntryForm2.setVisible(true);
        dataEntryForm2.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        }catch(Exception e){
            Popup popup=new Popup("please select one row");
            popup.setVisible(true);
            popup.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

            System.out.println("not selected");
        }
    }//GEN-LAST:event_addAmountButtonActionPerformed

    private void viewBillButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBillButtonActionPerformed
        // TODO add your handling code here:
         int[] selectedRow = jTable1.getSelectedRows();
         try{ 
        JDBCConnection.loadData(jTable1, jTable1.getValueAt(selectedRow[0],1).toString(), null, 0);
         }
         catch(Exception e){
             try{
          JDBCConnection.loadData(jTable1, jTable1.getValueAt(0,1).toString(), null, 0);
             }
             catch(Exception b){
                 Popup popup=new Popup("Data not available OR please select one row");
                 popup.setVisible(true);
                 popup.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

                 System.out.println("data not loaded");
             }
         }
         
    }//GEN-LAST:event_viewBillButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
         int[] selectedRow = jTable1.getSelectedRows();
         try{
        DataEntryForm2 dataEntryForm2=new DataEntryForm2(jTable1.getValueAt(selectedRow[0], 1).toString(),
        jTable1.getValueAt(selectedRow[0],2).toString(),jTable1.getValueAt(selectedRow[0],0).toString());
        dataEntryForm2.setVisible(true);
        dataEntryForm2.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
         }catch(Exception e){
             Popup popup=new Popup("Data not available OR please select one row");
                 popup.setVisible(true);
                 popup.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
         }

    }//GEN-LAST:event_updateButtonActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteActionPerformed

    public  void loadData(Boolean type){
        String sql="";
        if(type){
             sql = "SELECT Date,invoice,customer,type,total,cash,credit FROM jenudai where flag=1";
        }
        else{
             sql="SELECT Date,invoice,customer,type,total,cash,credit FROM jenudai where Date='"+new java.sql.Date(jDateChooser1.getDate().getTime())+"' AND flag=1";
        }
       try{
            Statement  stmt = conn.createStatement();
      ResultSet rs = stmt.executeQuery(sql);
            TableModel table=DbUtils.resultSetToTableModel(rs);
            jTable1.setModel(table);
        }catch(SQLException se){
      //Handle errors for JDBC
      se.printStackTrace();
   }catch(Exception e){
      //Handle errors for Class.forName
      e.printStackTrace();
   }  
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewRecords().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JButton addAmountButton;
    private javax.swing.JButton allButton;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton loadButton;
    private javax.swing.JButton updateButton;
    private javax.swing.JButton viewBillButton;
    // End of variables declaration//GEN-END:variables
}
